### ISSUE TITLE
1.x branch not compatible with PHP 8.1 due to return type enforcement of `\Iterable`

### ISSUE THREAD

**Issue by dpi** [rlanvin/php-rrule#102]
**Problems**

- 1.x branch is compatible with PHP 5.3 and above with contraint `"php": ">=5.3.0"`
- When running the 1.x branch with PHP 8.1, exceptions are thrown because `RSet` implements `Iterator`, but doesnt inherit its return types.
- Not all versions of PHP matching existing constraint (`>=5.3`) can use return types.

**Proposed solution**

- I dont think there is a 1.x branch? So perhaps create a legacy branch where the 2.x branch split off, at commit 1373df401e0926cf7548716dabbc0d19603a144d
- Add an entry to composer.json declaring the library incompatible with PHP 8, e.g with a `conflict` or limiting the PHP in `require` to `8.0.*`.

See also

 - https://stitcher.io/blog/new-in-php-81#interal-method-return-types-rfc
 - https://wiki.php.net/rfc/internal_method_return_types

**Comment by dpi** [comment]
See also a CI run with PHP 8.1 which revealed this issue: https://www.drupal.org/pift-ci-job/2249476. Note: PHP 8.0 is passing fine for this project.

**Comment by dpi** [comment]
There may be other compatibility issues, its just this project only happen to expose this one.

**Comment by dpi** [comment]
Putting this up for discussion first rather than creating a PR, since doing this will require a bit of Git manipulation. The changes themselves are rather simple to put together.

**Comment by rlanvin** [comment]
Hello, my apologies for the late answer. For some reason I didn't get the notifications on this project...
Is there any reason a version 1.x is still needed in this case? The version 2 is compatible with php 8.1 so I'm not really sure it's worth making a new 1.x release just to update the version constraint, but I'd like to understand the use case.

**Comment by heddn** [comment]
I assume it is for drupal module support. See https://www.drupal.org/project/date_recur. But I think we could switch to v2 branch.

**Comment by dpi** [comment]
Hi @rlanvin ,

At this point in time I'm ok this issue gets rejected, I have [a plan](https://www.drupal.org/project/date_recur#versions) for getting the [~4000 sites using this](https://www.drupal.org/project/usage/date_recur) onto v2. Hoping the beta phase uncovers any issues.

Was hoping to avoid issues, such as this one https://www.drupal.org/project/date_recur/issues/3267221 due to the broad PHP constraint in v1.

**Comment by rlanvin** [comment]
Ok thanks for the context.

The only thing that really changes in the v2 is the PHP version requirement. Internally it's using things like generator which didn't exist in previous PHP version, but everything else should be fully backward compatible and just a drop-in replacement of the v1. There are also a couple of bugs fixed in the later versions, which makes the upgrade definitely worthwhile.

With that said, I understand your point about the broad PHP constraint. In hindsight that was probably not the best idea to leave it open-ended and I'll put an upper limit from now on.

So what would help you guys here? A version 1.6.4 with a stricter constraint? Note that I would have no way to really test this fully since there won't be any CI pipeline (v1 used TravisCI, that I replaced with Github CI a while back), so it would just be releasing a bit blindly.
