### ISSUE TITLE
`getOccurrencesAfter` doesn't work with microseconds

### ISSUE THREAD

**Issue by edalzell** [rlanvin/php-rrule#104]
Hey there, not sure if this an actual bug.

I have found that if I set the `dtstart` to a time with microseconds (like `23:59:59.999999`), then the `nextOccurrencesAfter` will return the next day's occurrence and not today's occurrence.

Once I remove the microseconds, it works fine.

I'm setting `dtstart` to a Carbon instance:
<img width="725" alt="CleanShot 2022-04-10 at 20 50 33@2x" src="https://user-images.githubusercontent.com/6069653/162662299-cbf41ce5-3600-4a90-918e-75957973e366.png">

Where `endTime()` 	was `now()->endOfDay()->toTimeString('microsecond')`.

**Comment by rlanvin** [comment]
Hello, it's a bit hard to tell what's happening with the code your provided and without the exact rule, and on top of that `nextOccurrencesAfter` isn't part of this library, so I'm really confused.

Please provide the following:
- Reproducible code demonstrating the bug (including the rule), so I can try myself
- An example of expected behaviour vs actual behaviour
- The exact version of the library your are using

Thank you!

**Comment by edalzell** [comment]
With microseconds:
<img width="1332" alt="CleanShot 2022-04-14 at 19 21 31@2x" src="https://user-images.githubusercontent.com/6069653/163507700-b04bc095-b64d-4de8-a8ed-cb920fb8e2fc.png">

Without microseconds:
<img width="1286" alt="CleanShot 2022-04-14 at 19 21 57@2x" src="https://user-images.githubusercontent.com/6069653/163507750-bcf20e21-87c4-479a-b8a0-34074de19002.png">

Notice in the first screenshot, it shows TOMORROW (today is the 14th) and the second is correct.

**Comment by rlanvin** [comment]
Thank you for the details. Microseconds are known to cause issues with date comparison. The microsecond component was intended to be removed from the input, but you found a bug. I published version 2.3.1 which fixes this issue.

**Comment by edalzell** [comment]
Awesome, thanks for the quick fix. Love this package!
