### ISSUE TITLE
bi-weekly occurance wrong

### ISSUE THREAD

**Issue by hkkhchan** [rlanvin/php-rrule#140]
DTSTART:20230903T150000Z\nRRULE:FREQ=WEEKLY;BYDAY=TH;INTERVAL=2;UNTIL=20300401T160534Z
return is  [
    "Thu, 14 Sep 2023 15:00:00 +0000",
    "Thu, 28 Sep 2023 15:00:00 +0000",
    "Thu, 12 Oct 2023 15:00:00 +0000",
   ]
but the first day should be 7 Sep 2023

**Comment by rlanvin** [comment]
Looks like you want to specify WKST=SU then.

**Comment by hkkhchan** [comment]
> Looks like you want to specify WKST=SU then.

you are right. After specify WKST=SU, It work as my expection. But I still don't understand why I need to specify start day is Sunday, then the first day will be 7 Sep 2023. 7 Sep 2023 is the first date which meet the condition which is Thurday.

**Comment by rlanvin** [comment]
Because RFC 5545 defines the default WKST to Monday (according to ISO 8601). 

- You have a weekly frequency, so entire weeks are used to calculate occurrences
- The start date is Sunday, 3 September, which (by default) belongs to week 35 starting on Mon 28 Aug. So your first week is week 35.
- You have a BYDAY set to Thursday. Thursday in week 35 is 31 Aug which is before the start date (3 September) so this one doesn't count
- You have an interval of 2 so the next occurrence is in week 35+2 = 37 (starting Mon 11 Sep)
- The first occurrence in week 37 is Thu, 14 Sep

If you want the first occurrence to be 7 Sep 2023 you need to specify that your week start on Sundays. Then Sunday 3 Sep belongs to week 36, your rule starts on week 36 and the first Thursday on week 36 is indeed 7 Sep 2023
