### ISSUE TITLE
Looking for a way to add DTEND 

### ISSUE THREAD

**Issue by roycw** [rlanvin/php-rrule#145]
### GUys, we worked with this library for a while. amazing job.

I am well aware of the limitation per the RFC where DTEND is not supported.

However i do have the DTEND for my event and i was wondering if anyone can help with a boiler plate for the logic to add this end to the  Rset after the iterations.

i have an Rset i create like this 
```$rset->getOccurrencesBetween(@$input->begin ?: new DateTime("-1 day"), @$input->end ?: new DateTime('+31 day'));```

Id like to then iterate it and then patch my occurances with the DTEND.. my issue is that i dont know which occurrence was created with each rule... RSet includes alot of rules.

Any help would be appreciated

**Comment by rlanvin** [comment]
Hello,

Thanks for your message. So DTEND indicates the end of an event, and is not part of the RRULE property. Since every event in the recurrence is supposed to be the same duration, it doesn't impact the recurrence,. I am not aware of a way in the RFC 5545 to describe a recurring event, with some occurrences having a different DTEND.

Therefore in theory you can just calculate the DTEND by adding the duration of the event to the occurrence start date generated by the library. Years ago I wrote a small convenience wrapper with an Event class and a Proxy class as a proof of concept ([here](https://github.com/rlanvin/php-rrule/blob/proxy/tests/ProxyTest.php) - note the branch is outdated). The goal is exactly to do that, simply adding the duration automatically.

> my issue is that i dont know which occurrence was created with each rule... RSet includes alot of rules.

That's indeed not really possible, but I'm not sure - what would be your use case for this? Are your including rules referring to different events maybe? The RSet is modelled after the "recurrence set" described in RFC 5545 and is supposed to be used to combine multiple RRULE, RDATE and EXDATE for the _same_ event. Therefore you can apply the same technique describe above to just add the duration to each occurrence and have your DTEND.

If you're trying to use it for multiple different events... then it's indeed a bit tricky, because internally RSet works with DateTime objects (returned by RRule). If you wanted to "track" what occurrence comes from what rule, it would need to work with a higher level object containing not only the DateTime but also a reference to the rule that generated it (or the duration itself, to calculate the dtend). It might be possible to build on the PoC from the branch I linked above. Instead of giving RRule objects to RSet, using proxy class that implements the right interface and returns custom objects instead of DateTime, but those objects need to be comparable with each other like DateTime so RSet can sort the occurrences (and exclude ExDate...). Again, maybe possible, but not really designed to work like that.

Another possible approach I guess is to simply implement your own "event set" class so you can keep track of each DTEND for each occurrence generated. Internally RSet is using standard heap and iterators, and the entire logic is less than 100 lines, so it's quite straightforward to replicate.

Hope that helps!
