### ISSUE TITLE
Legacy Code - Can I 'require_once' instead of composer ?

### ISSUE THREAD

**Issue by marcoczen** [rlanvin/php-rrule#150]
Guys for legacy code, done by my predecessor, can I just 'require_once /path/to/some_php_file.php` ?
What would be the exact line ?

Thanks.

**Comment by rlanvin** [comment]
Composer exists since 14 years or something (~2012), how legacy is your code exactly?! The library is probably not going to work with code that old.

So frankly you should start with setting up Composer for your project and require the library as a package and use the auto-loader.

If for some reason you can't or don't want to, you will have to require the 5 PHP files contained in the `src` folder individually (so 5x require_once). But note that this is completely unsupported.

**Comment by marcoczen** [comment]
Thanks.
