### ISSUE TITLE
Accessing the properties...

### ISSUE THREAD

**Issue by jpmurray** [rlanvin/php-rrule#22]
Hello!

I was trying to access the DTSTART `datetime` object here, and so I went on and did the following:

```
$rule = new Rrule($show->rrule);
$dtstart = $rule['dtstart'];

// and sure enough, I get the datetime object.
```

Now I want to get, for the purpose of this issue, the count value.

```
// my first thought was to go and use this
$rule = new Rrule($show->rrule);
$values = $rule->getRule();
$count = $values['COUNT'];
// this works fine

//but if I do this...
$count = $rule['count']
// the return value is the datetime object for DTSTART
```

Is this... Normal behavior? I mean, if I can access the DTSTART property like so, I'd expect the others to be available too.

**Comment by rlanvin** [comment]
> Is this... Normal behavior?

Well yes.

The array access operator is meant to access occurrences by index, not properties of the object. So if you want to access the Nth occurrence, you use `$rule[N]`. E.g. the 3rd occurrence is `$rule[2]`. More info [on the wiki](https://github.com/rlanvin/php-rrule/wiki/RRule#array-access).

What's happening is when you use `$rule['dtstart']`, PHP understands `$rule[0]` due to loose typecasting. `$rule[0]` is the first occurrence of the set, which incidentally is your `dtstart`. Note that it could be something else as well, depending on the rule.

**Comment by jpmurray** [comment]
RIGHT! Thank you for that clarification, I just couldn't wrap my mind around that... It's one of these days! :)

**Comment by jpmurray** [comment]
But then... I might just be a lousy wiki reader, but isn't there a method to get the `datetime` object of the rule that I didn't see? I'm just _so sure_ I used one in the past, but yeah, it might just be that I misused the array access...

**Comment by jpmurray** [comment]
AH! That's why!

`$rrule->getRule()['DTSTART']` returns value passed by constructor! I had some part of the code where I sent a `datetime` object, and I reused the code somewhere where I instantiated with a Rrule string!

Now it's clear for me! :D

**Comment by rlanvin** [comment]
Good! Note that if you pass a RFC String to the constructor, you will get a `datetime` object for `DTSTART`. The situations where you would not get a `datetime` object are if you used an array, with the `DTSTART` key a string ,e.g. "2017-01-01".

I added checks to `offsetGet`, now it'll throw an `InvalidArgumentException` for illegal offset types, which should avoid confusion.
