### ISSUE TITLE
Create Exrule ranges

### ISSUE THREAD

**Issue by guillaumevoisin** [rlanvin/php-rrule#33]
Would it be possible to exclude a range of days from a recurrence.
*Example*

```
DTSTART:20170501T090000Z
RRULE:FREQ=WEEKLY;UNTIL=20170531T090000Z;BYDAY=MO,TU
EXRULE:FREQ=WEEKLY;DTSTART=20170508T120000Z;UNTIL=20170509T140000Z;BYDAY=MO
```

I want to add a recurrence for the whole month of May but exclude a period on the 9th between 12PM and 2PM, or even a longer period from May 8th to May 9th.

As of today, I can't add a DTSTART in an EXRULE, so could I determine a start for the exception ?
Do I need to add as many EXDATE as there are in the range ?

**Comment by rlanvin** [comment]
Is your question about this lib in particular or about the RFC?

There is a slight difference between how the lib works and what the RFC says in regards to DTSTART.

In the RFC, there can only be one DTSTART (as in your example).

In the lib however, the DTSTART are *per RRule objects* so a RSet object actually contains more than one DTSTART (this causes a problem when trying to export the RSet as a RFC-compliant string by the way, and this is why the method to export a RSet as a string is not available yet).

> As of today, I can't add a DTSTART in an EXRULE, so could I determine a start for the exception ?

Yes, as I explained above, using the lib only, and forgetting about the RFC compliance, you can absolutely do that. Add a new RRule object as an EXRULE with a different DTSTART.

In order to be RFC compliant, I need to implement the ["PERIOD" syntax for RDATE and EXDATE](https://tools.ietf.org/html/rfc5545#page-121) which takes 2 dates, and does pretty much what you want. It's not an easy task though, and at the moment I'm not sure how to do it.

> Do I need to add as many EXDATE as there are in the range ?

At the moment, if you want to be RFC compliant, I'm afraid that is indeed the only option.
