### ISSUE TITLE
date_default_timezone_set('Europe/Helsinki'); breaks further tests

### ISSUE THREAD

**Issue by gregor-tb** [rlanvin/php-rrule#42]
Running RRuleTest on non-isolated environment may break other tests/behaviour, by not reverting to default after test ends.

**Comment by rlanvin** [comment]
Ok I'll have a look but I'm not sure what you mean by "non-isolated environment". Do you mean you are running the tests of this library within some other tests? I'm curious to know your use case for this.

**Comment by gregor-tb** [comment]
yeah exactly, I run all tests at once in jenkins

**Comment by rlanvin** [comment]
I'm still not sure I understand *why* you are doing this. Are you running all the tests of all the 3rd party librairies of your project? How can they all run within the same PHP process without failing or conflicting with each others? Just being curious because I've never heard of such a use case before.

Anyway, the reason why it's done that way (and not in `setUpBeforeClass` like I originally intended it) is because in PHPUnit's data providers are called before `setUpBeforeClass` (it's a documented behaviour). Since the data providers in this test suite create a lot of DateTime objects, the default timezone must be set before they are executed... As far as I know, this means setting it globally (granted, this could be in the bootstrap file instead).

I'm open to suggestions if you know a clean way how to solve this.

**Comment by rlanvin** [comment]
Closing this ticket, given that it doesn't seem to be a real problem.
