### ISSUE TITLE
Monthly Recurring Rules Behavior?

### ISSUE THREAD

**Issue by IndependentITLLC** [rlanvin/php-rrule#55]
How does this library handle monthly recurrences on the 29th-31st days, over months which don't have those days? Does it skip them, or default to the last day in that month? Is this configurable?

ie
`2013-01-31, 2013-02-28, 2013-03-31, 2013-04-30, 2013-05-31`
or
`2013-01-31, ___skipped, 2013-03-31, ___skipped, 2013-05-31`

This discusses the issue, and a solution I think:
[rfc7529 #section-4.1](https://tools.ietf.org/html/rfc7529#section-4.1)
So I suppose my question is ultimately, has SKIP been implemented?

**Comment by rlanvin** [comment]
The lib is based on RFC 5545 so invalid dates generated while iterating the rule are ignored. However in your example you would easily get the last day of the month with `BYMONTHDAY=-1` instead.

This behavior is not configurable, and `SKIP` has not been implemented - in fact to be honest I hadn't heard about RFC 7529 until now.

**Comment by rlanvin** [comment]
Did you try `RSet`? Because I think this could be achieved with the `RSet` class that allows combining multiple rules, e.g. "29th of every month" + "every last day of February". While I agree it's not as elegant, it's nevertheless doable.

> Is there any hope that RFC 7529 might be integrated(unsure of word choice) in the future?

As much as I would like to say yes, I honestly believe this is highly unlikely. The problem is that a date such as 30 February doesn't not *exists*. It's not "skipped" by the algorithm (and we could somehow modify it to, let's say, replace it by the previous valid date instead of "skipping" it), no, instead it isn't considered *at all*. So to implement `SKIP` would require (I think, based on a quick assessment) a major rewrite of the core algorithm. On top of that, most helpers functions (such as `occursAt`) would also need to be rewritten because a date that does not match the rule according to RFC 5545, actually could maybe match the rule according to RFC 7529 depending on the `SKIP` parameter. The cherry on top of the cake is that the RFC states that `SKIP` must only be used when `RSCALE` is present, and that comes with a gazillion of other issues...

The use case for this `SKIP` is extremely narrow (if I understand correctly is only about leap days and "last day of the month" type of rules) so I don't think it's worth such an extensive rewrite and all the problems associated with it.

**Comment by IndependentITLLC** [comment]
I understand, thank you for the consideration.
I do believe I could make something work with RSet, and that might be what I end up doing ultimately.
