### ISSUE TITLE
Setters for RSet attributes

### ISSUE THREAD

**Issue by rickywiens** [rlanvin/php-rrule#65]
We have a use-case where we want to remove ExDates and RDates from RSets. The most simple way to do this in my opinion would be to add setters for RSet attributes into the RSet class. If I made a PR with that functionality & tests for it, would that be something that would be accepted?

Further, we have some code that pieces together an RFC string from an RSet, however, like was mentioned [here](https://github.com/rlanvin/php-rrule/issues/26) it needs to be opinionated about how to reconstruct it (remove DTStarts from RRules, and keep the top level DTStart). If I made a PR adding that functionality into the RSet class, noting specifically that some functionality is not supported (multiple DTStarts) would that be accepted?

**Comment by rlanvin** [comment]
Hello, thank you for asking :-) To answer specifically to your 2 suggestions:

- Creating a RFC string from an RSet is a feature that has been requested multiple times. Indeed it needs to be opinionated. I think the safest way would be to throw an exception if the RSet contains multiple different DTSTART because ignoring different DTSTART might lead to a RSet string representation that would not produce the same results if parsed again into a RSet. Anyway I'd love to have a PR on that, and I can add comment during code review. 

- Adding setters for RSet attributes... probably not. I feel it will expose too much of the internal implementation of the class, and create an alternative way to use the class (instead of using add* methods you would also be able to use set* methods).
However I think the use case is valid. So what about methods like "removeExDates()" that removes everything, and/or (depending of the use case) other methods like "removeExDate($date)" that only removes the date given as an argument?

As a general rule, I expect the PR to contain tests (which you mentioned) and follow the existing coding style and naming, because I like keeping the code base somewhat consistent. Before accepting any PR I do a code review, and I might request some changes, but as long as your are open to amending your PR there shouldn't be any problem. I'd also ask you to base your PR on the latest master (version 2) because I don't want to maintain a 1.x branch.

Let me know if you have any question/concerns.

**Comment by rickywiens** [comment]
Sounds great! :) Thanks for the response, we will see what we can cook up.

**Comment by rickywiens** [comment]
Hey @rlanvin , just wondering if you had a moment to look over my PR?

**Comment by rlanvin** [comment]
@rickywiens Done 👍

**Comment by rlanvin** [comment]
@rickywiens I'm closing this ticket now, but feel free to open a PR if you want to work on the first part.
