### ISSUE TITLE
EXDATE support

### ISSUE THREAD

**Issue by gustavs-gutmanis** [rlanvin/php-rrule#7]
Hi, I was wondering if [EXDATE](http://www.kanzaki.com/docs/ical/exdate.html) is something you would consider implementing?

Thanks.

The library is fantastic, by the way.

**Comment by rlanvin** [comment]
Yes why not. It's not strictly part of the RRULE string. The way the Python lib did it, is to implement a `rruleset` class, that can take multiple RRULE, RDATE, EXRULE and EXDATE (see [here](https://labix.org/python-dateutil#head-f83f4f0dd5fa533e0260bdcdd08df927594c32d2)). It seems the most logical approach, so I think I would do the same with a `RRule\Set` class for example. Are you asking because you want to start working on a pull request?

> The library is fantastic, by the way.

Thanks. Most of the credit goes to the author of the original Python version though, I only adapted it to PHP. :)

**Comment by gustavs-gutmanis** [comment]
I would love to but currently I've got enough on my plate, I was asking to see if maybe you have that on your agenda :)

**Comment by rlanvin** [comment]
@gustavs-gutmanis There is an implementation (almost complete) of recurrence set in dev-master. I also started to update the wiki. Feel free to test it and give feedback!

**Comment by gustavs-gutmanis** [comment]
You are a wonderful person! I'll give it a shot tomorrow morning.
