### ISSUE TITLE
Getting the X *most recent* occurrences?

### ISSUE THREAD

**Issue by Grayda** [rlanvin/php-rrule#87]
I'm working on a project and would like to get the last X number of occurrences to display to the end user, but I can't seem to work out if that's possible.

As an example, I'm using the RRULE `FREQ=MINUTELY`

My first thought was to just call `getOccurrencesBefore($now, false, $num)`, but that returns an empty array if no `DTSTART` is set. If one is set, then it just returns the first `$num` occurrences.

I also thought about `getOccurrencesAfter($now - $someAmountOfTime, false, $num)` and `getOccurrencesBetween` but those wouldn't work if I set `$someAmountOfTime` to 1 day / 10 days / 100 days, and the user had an even that only occurred once every 6 months.

I've got a column in my database that records when the last event took place, but that's mostly for logging purposes, and if the user created the event a minute ago, they can't see when the event would have taken place in the past.

So is what I'm asking for possible?

**Comment by rlanvin** [comment]
> My first thought was to just call getOccurrencesBefore($now, false, $num), but that returns an empty array if no DTSTART is set.

This is because when there is no DTSTART, then the current date is implicitly used as DTSTART. So this is correct, there is no occurrences before "now".

> I also thought about getOccurrencesAfter($now - $someAmountOfTime, false, $num)

Also wouldn't work, because again DTSTART would implicitly be set to now. This will of course produce results, but `- $someAmountofTime` has no literally effect on the results, they will always start from now.

> So is what I'm asking for possible?

Kind of. The thing is, RRule cannot be computed without a DTSTART to use as an the start point of the algorithm. The entire algorithm is an iterator that walks the occurrences in chronological order. `getOccurrencesBefore` actually calculates all the occurrences up until that point in time, and simply return the slice you are interested in.

What you are asking, and trying to do here, is basically reversing the entire calculation and starting from the end instead, without a known start. The only solution I can think of would require writing a reverse iterator and basically reversing the entire flow of the algorithm. Good luck with that :-)

That said you could write your own brute-force algorithm to work around this. Something like (pseudo code):
```
DTSTART = today
do
  DTSTART = DTSTART - 1 year
  create a rule with DTSTART
  resultset = get X occurrences before now.
repeat until resultset contains X occurences
```

**Comment by Grayda** [comment]
Thanks for answering that. Your pseudocode sounds somewhat workable. I'll give it a shot and see how I go.

I hadn't had a chance to read the source code yet, so I was wrongly assuming that a "work backwards" feature wouldn't involve much (just setting the start date as now, working out the interval and inverting it (e.g. instead of +1 day, use -1 day instead), but it sounds like there'll be more work than that involved.
