### ISSUE TITLE
occursAt not reaching date without time

### ISSUE THREAD

**Issue by StefanYohansson** [rlanvin/php-rrule#88]
I am having trouble calling occursAt with the following snippet.

recurrence string: `string(34) "RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=MO"`

```
$today = (new \DateTime('2020-11-16'))->format('Y-m-d');
$rule = RRule::createFromRfcString("RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=MO");
$rule->occursAt($today)
```
occursAt in this case returns `false` but `$rule->getOccurrencesBetween('2020-11-01', '2020-11-30')` returns

```
array(2) {
[0]=>
object(DateTime)#203 (3) {
["date"]=>
string(26) "2020-11-16 15:11:17.000000"
["timezone_type"]=>
int(3)
["timezone"]=>
string(17) "America/Fortaleza"
}
[1]=>
object(DateTime)#200 (3) {
["date"]=>
string(26) "2020-11-23 15:11:17.000000"
["timezone_type"]=>
int(3)
["timezone"]=>
string(17) "America/Fortaleza"
}
}
```

and 2020-11-16 is there. I think it is something related to I am not passing the time to datetime :thinking:

**Comment by StefanYohansson** [comment]
Drill down the problem I found it is hitting there

https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L761-L764

putting a var_dump on $this and $this->byhour

$this
```
object(RRule\RRule)#192 (21) {
  ["rule":protected]=>
  array(15) {
    ["DTSTART"]=>
    NULL
    ["FREQ"]=>
    string(6) "WEEKLY"
    ["UNTIL"]=>
    NULL
    ["COUNT"]=>
    NULL
    ["INTERVAL"]=>
    int(1)
    ["BYSECOND"]=>
    NULL
    ["BYMINUTE"]=>
    NULL
    ["BYHOUR"]=>
    NULL
    ["BYDAY"]=>
    string(2) "MO"
    ["BYMONTHDAY"]=>
    NULL
    ["BYYEARDAY"]=>
    NULL
    ["BYWEEKNO"]=>
    NULL
    ["BYMONTH"]=>
    NULL
    ["BYSETPOS"]=>
    NULL
    ["WKST"]=>
    string(2) "MO"
  }
  ["dtstart":protected]=>
  object(DateTime)#193 (3) {
    ["date"]=>
    string(26) "2020-11-15 15:20:33.000000"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(17) "America/Fortaleza"
  }
  ["freq":protected]=>
  int(3)
  ["until":protected]=>
  NULL
  ["count":protected]=>
  NULL
  ["interval":protected]=>
  int(1)
  ["bysecond":protected]=>
  array(1) {
    [0]=>
    int(33)
  }
  ["byminute":protected]=>
  array(1) {
    [0]=>
    int(20)
  }
  ["byhour":protected]=>
  array(1) {
    [0]=>
    int(15)
  }
  ["byweekday":protected]=>
  array(1) {
    [0]=>
    int(1)
  }
  ["byweekday_nth":protected]=>
  array(0) {
  }
  ["bymonthday":protected]=>
  NULL
  ["bymonthday_negative":protected]=>
  NULL
  ["byyearday":protected]=>
  NULL
  ["byweekno":protected]=>
  NULL
  ["bymonth":protected]=>
  NULL
  ["bysetpos":protected]=>
  NULL
  ["wkst":protected]=>
  int(1)
  ["timeset":protected]=>
  array(1) {
    [0]=>
    array(3) {
      [0]=>
      int(15)
      [1]=>
      int(20)
      [2]=>
      int(33)
    }
  }
  ["total":protected]=>
  NULL
  ["cache":protected]=>
  array(0) {
  }
}
```
$this->byhour
```
array(1) {
  [0]=>
  int(15)
}
```

i don't understand right now what byhour mean here since my recurrence string doesn't mention anything about that.

**Comment by rlanvin** [comment]
Hello,

> seems that lack of DTSTART on my recurrence string causes the library to use new DateTime() as default and use some default on byhour

This is correct. I agree this is a surprising, but this is more or less the intended behaviour.

1. The RRule constructor derives the year/month/day/hour/minutes/seconds constraints from DTSTART (the DTSTART is only a date, time component is 00:00:00 by default).
2. When no DTSTART is provided, the constructor will use a full datetime as DTSTART, so it gets initialized with a time component.
3. When you pass a date only to occursAt, the time components do not match. It compares "now", e.g. 11:27:00, to 00:00:00 which obviously are not equal.

Workaround:

Instead of `RRule::createFromRfcString("RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=MO");` use `new RRule("RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=MO",$today);` - so you explicitely pass a DTSTART without a time component.

Proper fix:

I'm not sure there is a proper fix. This behaviour is inherent to the fact that 1) PHP only has `DateTime` object (so you always have to carry around a time component) and 2) this lib has a flexible API that accept a lot of different input and fill up the blank with some sensible default. In this case the default behaviour (using a full datetime) doesn't work with your use case, so you have to be explicit when you instantiate the object that you don't want to work with time (so set the time to 00:00:00).

That said, I'm always open to suggestions if you have an idea how to improve this.

**Comment by StefanYohansson** [comment]
Thank you, your suggestion definitely solves my problem. Maybe we should document this specific behaviour on README or somewhere else.

Closing since it solves the problem.
